### ISSUE TITLE
Dell 3040 i3-6100T

### ISSUE THREAD

**Issue by felipe-developer** [DevHuney/EFI-OptiPlex3040#1]
Salve meu bom, conseguir fazer com processador i3-6100T e 6GB de ram mas tenho percebido que dar umas travadas não sei ser e por causa do processador ou placa de video, mas muito obrigado eu so conseguir por causa da sua EFI obrigado

**Comment by DevHuney** [comment]
Por nada meu amigo, logo lançarei uma nova versão da EFI, ela atualizadinha, obrigado pela sua atenção.

**Comment by huneyoliv** [comment]
Por nada meu amigo, logo lançarei uma nova versão da EFI, ela atualizadinha, obrigado pela sua atenção.
